name: PR Preview

on:
  pull_request:
    branches:
      - "**"

jobs:
  build-and-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: python main.py

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0

      - name: Create preview directory
        run: |
          mkdir -p gh-pages/pr-preview/pr-${{ github.event.pull_request.number }}

      - name: Copy files to preview directory
        run: |
          cp -r web-page/* gh-pages/pr-preview/pr-${{ github.event.pull_request.number }}/

      - name: Commit and push changes
        run: |
          cd gh-pages
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add preview for PR #${{ github.event.pull_request.number }}"
            git remote set-url origin https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
            git push
          fi

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = `https://${context.repo.owner}.github.io/${context.repo.repo}/pr-preview/pr-${context.payload.pull_request.number}/`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview deployed to: ${previewUrl}`
            });
