name: Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: python main.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-page
          path: web-page/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: web-page
          path: web-page/

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Checkout gh-pages
      run: |
        git checkout gh-pages

      - name: Copy files
      run: |
        rsync -rc --existing --delete web-page/ ./

    - name: Check for changes
      id: check_changes
      run: |
        git status --porcelain
        if [[ $(git status --porcelain) ]]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Commit and push changes
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Update gh-pages"
        git push
