name: Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: python main.py

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          persist-credentials: false
          fetch-depth: 0

      - name: Prepare gh-pages
        run: |
          rm -rf gh-pages/*
          cp -r web-page/* gh-pages/
          cd gh-pages
          echo "deploy=$(date +'%Y-%m-%d %H:%M:%S')" >> .nojekyll

      - name: Setup credentials to access private repositories
        run: git config --global url.https://${{ secrets.PAT }}@github.com/.insteadOf https://github.com/

      - name: Commit and Push changes
        run: |
          git add .
          git diff --quiet --exit-code || git commit -m "Update gh-pages"
          git push origin gh-pages -u origin gh-pages --force
        working-directory: ./gh-pages
