name: Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: python main.py

      - name: Checkout gp-pages branch
        uses: actions/checkout@v4
        with:
          ref: gp-pages
          path: gp-pages

      - name: Copy files to gp-pages branch
        run: |
          rm -rf gp-pages/*
          cp -r web-page/* gp-pages/

      - name: Commit and push changes
        run: |
          cd gp-pages
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update website content"
            git push origin gp-pages
          fi
